### ISSUE TITLE
Add Background process

### ISSUE THREAD

**Issue by prathmeshgat** [heroku-examples/python-miniconda#1]
I am trying to integrate Background process into my flask application as per this documentation(https://devcenter.heroku.com/articles/python-rq) . Since I am using docker (https://github.com/heroku-examples/python-miniconda) to deploy my app there is no Procfile. But the steps in the documentation(https://devcenter.heroku.com/articles/python-rq) says that I need to add:-
worker: python worker.py to ProcFile.

Since I dont have ProcFile I am not able to integrate Background process into my flask application. Please advise me how can this be achieved using docker deployment?

**Comment by kennethreitz** [comment]
You need to change the Dockerfile to reflect what you want the process type to be, then do:

    $ heroku container:push worker
