### ISSUE TITLE
Building image using heroku.yml

### ISSUE THREAD

**Issue by pinders** [heroku-examples/python-miniconda#3]
I tried building and deploying this app using a heroku.yml and the normal git push heroku... my heroku.yml looks like this:

```
build:
  docker:
    web: Dockerfile
```
Pushing and building the image works, but during runtime I get the following error:

`IOError: [Errno 13] Permission denied: '/opt/conda/lib/python2.7/site-packages/.wh.conda-4.2.15-py2.7.egg-info'`

Could someone advise me how to resolve this error?

**Comment by kennethreitz** [comment]
You are using a developer preview of a feature that is in active development.

Please email heroku-build-manifest-feedback@salesforce.com to provide any feedback that you have.
